# Create and test a Python package on multiple Python versions.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  batch: 'true'
  branches:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - '*.md'

strategy:
  matrix:
    Python35:
      python.version: '3.5'
      os.version: 'ubuntu-latest'
    Python36:
      python.version: '3.6'
      os.version: 'ubuntu-latest'
    Ubuntu:
      python.version: '3.7'
      os.version: 'ubuntu-latest'
    Windows:
      python.version: '3.7'
      os.version: 'vs2017-win2016'
    Mac:
      python.version: '3.7'
      os.version: 'macOS-10.14'


pool:
  vmImage: '$(os.version)'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install pytest coverage
  displayName: 'Install & Upgrade pip'

- script: |
    coverage run -m pytest pyderman/test.py --doctest-modules --junitxml=junit/test-results.xml
    coverage report
  displayName: 'Test with pytest'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'